### ISSUE TITLE
processed image grid is not saved to output directory (left in temp)

### ISSUE THREAD

**Issue by jmp909** [glucauze/sd-webui-faceswaplab#10]
**Describe the bug**
processed image grid is not saved to output directory .. remains in eg `%AppData%\Local\Temp\Gradio`

**To Reproduce**
* run a generaton with a `batch size` of eg 4 images 
* Observe pre-processed grid is output to correct directory,  but the processed grid remains in the temp gradio folder

**Expected behavior**
Post-process image grid should be output to relevant directory
(Note: ideally pre-processed image grid should only be output if "Keep original image before swapping" is checked)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera GX

thanks

**Comment by glucauze** [comment]
That's true, i do not save the grid in current version :

```python
                # Generate grid :
                if opts.return_grid and len(images) > 1:
                    grid = imgutils.create_square_image(images)
                    text = processed.infotexts[0]
                    infotexts.insert(0, text)
                    if opts.enable_pnginfo:
                        grid.info["parameters"] = text
                    images.insert(0, grid)
```

Will try to fix that in next version.
