### ISSUE TITLE
Batch Sources Images ,  uploading

### ISSUE THREAD

**Issue by CristianoTian** [glucauze/sd-webui-faceswaplab#106]
![image](https://github.com/glucauze/sd-webui-faceswaplab/assets/28949154/8d51a14b-0afc-4c36-bbaf-557b0a1e5922)

Been uploading for over an hour

**Comment by glucauze** [comment]
This is a gradio bug i think. Try restarting or try to run.

**Comment by CristianoTian** [comment]
> 

have restarted，and uploading always

**Comment by glucauze** [comment]
I have no idea, never seen that bug and hard to fix with so few clues.
