### ISSUE TITLE
Is this extension possible for using with API ? alwayson_scripts

### ISSUE THREAD

**Issue by duoqbao** [glucauze/sd-webui-faceswaplab#11]
I checked out script-info by get from '/sdapi/v1/script-info'.
I try to post to '/sdapi/v1/txt2image this with 
```
alwayson_scripts: {
    faceswaplab: {
      args: args,
    },
  },
```
In processing FaceSwapLab not work.

**Comment by glucauze** [comment]
There's a dedicated API : https://github.com/glucauze/sd-webui-faceswaplab/blob/main/client_api/faceswaplab_api_example.py. I'm not sure that the basic API works well because of the large number of parameters. I'll look at it later.
