### ISSUE TITLE
Ways to improve gender-matching controls

### ISSUE THREAD

**Issue by Benjamin1973** [glucauze/sd-webui-faceswaplab#110]
Kudos on awesome project.  I'm enjoying it a lot!

Since automatic gender guessing on checkpoint creation is sometimes wrong (e.g. it thinks my wife is a man!), please do one or both of:

1) **Allow arbitrary gender assignment on training a new checkpoint**, rather than letting the model decide.

AND/ OR

2) Add a "match to female / match to male" option instead of just "Same Gender" in the Face settings.

**Comment by glucauze** [comment]
This is already possible in checkpoint builder

**Comment by Benjamin1973** [comment]
I've just updated, and I have the following on my Tools/Build tab: Batch Sources Images, Preview, Name of Character, Overwrite Checkpoint.  I cannot see any gender-setting options.

Am I missing a setting somewhere to enable advanced options or something?

**Comment by Benjamin1973** [comment]
Oh wow I'm stupid.  I updated and restarted UI, but it didn't "stick."  Just restarted Auto1111.

Couldn't be happier, you rock!

Since I have you, I have a question-- can I Batch a folder?  I can only see selecting individual files, but limit seems to be about 1000.  Great for image folders, but not good for long set of movie stills.

**Comment by glucauze** [comment]
I don't have on options for batch folder no. I used the gradio features that are not really perfect. Might be done in the futur.

**Comment by Benjamin1973** [comment]
Oh I see, limitations of the framework, I understand.

How about this-- batch by list of faces?  So it would make a new folder for each face, and re-batch.

**Comment by glucauze** [comment]
The easier would be to add a batch dir option in the batch source. By gradio not perfect, i mean the interface for dropping could be improved. You probably could use the API in the meantime to avoid that but that would require more work.

**Comment by Benjamin1973** [comment]
Well, my issue is with the number of files max-- about 1000.  A movie would have potentially 60 frames / sec * 3600 sec / hr * 1.5 = gonna be a burden if you have to select them 1000 at a time.

**Comment by glucauze** [comment]
There are probably better tools for movies right now :)

https://github.com/RichardErkhov/FastFaceSwap
https://github.com/facefusion/facefusion

Anyway, you can probably use API in the meantime : https://github.com/glucauze/sd-webui-faceswaplab/blob/main/client_api/faceswaplab_api_example.py
