### ISSUE TITLE
Excluding the model loading time, how long does inference take on T4 GPU?

### ISSUE THREAD

**Issue by johnlee6511** [glucauze/sd-webui-faceswaplab#128]
Hello!

I want to optimize inference time.
How long does inference take on T4 GPU for single image?

I takes 14 seconds excluding loading model.
There are any technique to reduce the time?

Thanks!

**Comment by glucauze** [comment]
Did you check GPU is really used and CUDA provider is selected ? It should be enabled on settings too. That's surprisingly slow. Without upscaling it should be less than 2s. It is the case on my RTX3080ti. I don't have experience with T4. I will check on a M40 if i have time.
