### ISSUE TITLE
Why the image has some patches?

### ISSUE THREAD

**Issue by yangdeai** [glucauze/sd-webui-faceswaplab#129]
I used the txt2img with a image, but the genrated image with some patches?
Is anything wrong?

**Describe the bug**
![00017-607307707-swapped](https://github.com/glucauze/sd-webui-faceswaplab/assets/55951120/d9cc27d2-1455-42b9-9444-610e45ac4b74)
![00018-3975453951-swapped](https://github.com/glucauze/sd-webui-faceswaplab/assets/55951120/63dbcce6-0e93-4897-9156-ac4e931588f0)

**To Reproduce**

prompt
a portrait of woman

the reason is the below? because I set the upsampler to Lanczos, the patches disappear.
 - FaceSwapLab - WARNING - Please note that improved mask does not work well without upscaling. Set upscaling to Lanczos at least if you want speed and want to use improved mask.

**Comment by glucauze** [comment]
See https://github.com/glucauze/sd-webui-faceswaplab/issues/38
