### ISSUE TITLE
Install Errors

### ISSUE THREAD

**Issue by WeirdScienceX** [glucauze/sd-webui-faceswaplab#17]
**Describe the bug**
Traceback Errors during install

**To Reproduce**
1. Install from extensions tab

**Expected behavior**
Successful install

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Firefox 117.0b1

**Additional context**
*** Error running install.py for extension C:\AI\stable-diffusion-webui\extensions\sd-webui-faceswaplab.
*** Command: "C:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "C:\AI\stable-diffusion-webui\extensions\sd-webui-faceswaplab\install.py"
*** Error code: 1
*** stdout: Checking faceswaplab requirements
*** Install opencv-python==4.7.0.72
*** Installing sd-webui-faceswaplab requirement: opencv-python==4.7.0.72
*** Install pydantic==1.10.9, 1.10.8 vs 1.10.9
*** Installing sd-webui-faceswaplab requirement: changing pydantic version from 1.10.8 to 1.10.9
*** Couldn't install sd-webui-faceswaplab requirement: changing pydantic version from 1.10.8 to 1.10.9.
*** Command: "C:\AI\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install pydantic==1.10.9 --prefer-binary
*** Error code: 1
*** stdout: Collecting pydantic==1.10.9
***   Using cached pydantic-1.10.9-cp310-cp310-win_amd64.whl (2.1 MB)
*** Requirement already satisfied: typing-extensions>=4.2.0 in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from pydantic==1.10.9) (4.6.2)
*** Installing collected packages: pydantic
***   Attempting uninstall: pydantic
***     Found existing installation: pydantic 1.10.8
***     Uninstalling pydantic-1.10.8:
***       Successfully uninstalled pydantic-1.10.8
***
*** stderr: WARNING: Ignoring invalid distribution -rotobuf (c:\ai\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\ai\stable-diffusion-webui\venv\lib\site-packages)
*** ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\AI\\stable-diffusion-webui\\venv\\Lib\\site-packages\\~ydantic\\annotated_types.cp310-win_amd64.pyd'
*** Check the permissions.
***
***
*** [notice] A new release of pip is available: 23.1.2 -> 23.2.1
*** [notice] To update, run: C:\AI\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
***
*** Warning: Failed to install pydantic==1.10.9, faceswaplab will not work.
***
*** stderr:
*** Downloading:   0%|          | 0.00/529M [00:00<?, ?B/s]
*** Downloading:   0%|          | 8.00k/529M [00:00<5:14:09, 29.4kB/s]
--snip--
*** Downloading: 100%|#########9| 528M/529M [02:09<00:00, 4.56MB/s]
*** Downloading: 529MB [02:09, 4.29MB/s]
*** Traceback (most recent call last):
***   File "C:\AI\stable-diffusion-webui\extensions\sd-webui-faceswaplab\install.py", line 66, in <module>
***     raise e
***   File "C:\AI\stable-diffusion-webui\extensions\sd-webui-faceswaplab\install.py", line 58, in <module>
***     launch.run_pip(
***   File "C:\AI\stable-diffusion-webui\modules\launch_utils.py", line 136, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "C:\AI\stable-diffusion-webui\modules\launch_utils.py", line 113, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install sd-webui-faceswaplab requirement: changing pydantic version from 1.10.8 to 1.10.9.
*** Command: "C:\AI\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install pydantic==1.10.9 --prefer-binary
*** Error code: 1
*** stdout: Collecting pydantic==1.10.9
***   Using cached pydantic-1.10.9-cp310-cp310-win_amd64.whl (2.1 MB)
*** Requirement already satisfied: typing-extensions>=4.2.0 in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from pydantic==1.10.9) (4.6.2)
*** Installing collected packages: pydantic
***   Attempting uninstall: pydantic
***     Found existing installation: pydantic 1.10.8
***     Uninstalling pydantic-1.10.8:
***       Successfully uninstalled pydantic-1.10.8
***
*** stderr: WARNING: Ignoring invalid distribution -rotobuf (c:\ai\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\ai\stable-diffusion-webui\venv\lib\site-packages)
*** ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\AI\\stable-diffusion-webui\\venv\\Lib\\site-packages\\~ydantic\\annotated_types.cp310-win_amd64.pyd'
*** Check the permissions.
***

**Comment by glucauze** [comment]
This seems to be an env problem and may be linked to the pydantic version. I've made changes in the next versions. We'll see if that solves the problem.

**Comment by WeirdScienceX** [comment]
Restarting did enable the installation to proceed, and it seems to work as normal, but I only had a brief time to test it.
