### ISSUE TITLE
How do I build a checkpoint with multiple angles of a face?

### ISSUE THREAD

**Issue by Xxredz** [glucauze/sd-webui-faceswaplab#186]
It only allows me to add one face in the Build tab at a time. How do I build a checkpoint of multiple individual images of the same face?

**Comment by TexNorwegian** [comment]
Drag and drop the amount of faces you want to build into that box. If the faces are too close up, meaning edges of faces are cut off, then it won't build.

**Comment by Xxredz** [comment]
> Drag and drop the amount of faces you want to build into that box. If the faces are too close up, meaning edges of faces are cut off, then it won't build.

Sorry but this isn't working? I'm in the build tab and drag a face image into the Batch Source Images area which works and then I try to drag a second face image in there and it just opens a new tab and doesn't add it to the list?

Edit: Never mind, I solved it. You have to drag in all the images at once.
