### ISSUE TITLE
"Check onnxruntime-gpu is installed" error?

### ISSUE THREAD

**Issue by kelkun01** [glucauze/sd-webui-faceswaplab#201]
Hello just wanted to check if anyone knows what this error is when running FSL

 "CUDAExecutionProvider not found in onnxruntime.available_providers : ['AzureExecutionProvider', 'CPUExecutionProvider'], use CPU instead. Check onnxruntime-gpu is installed"
 
 I already tried installing onnxruntime-gpu by runnning 'pip install onnxruntime' - not sure what I'm missing

**Comment by inlibiti** [comment]
How did you solve it? I also get the same error.
