### ISSUE TITLE
version 1.2.0 is not as good as 1.1.2 ，the swaped face is very blur, and more complex operation

### ISSUE THREAD

**Issue by glucauze** [glucauze/sd-webui-faceswaplab#25]
version 1.2.0 is not as good as 1.1.2 ，the swaped face is very blur, and more complex operation

_Originally posted by @sdcarterchen in https://github.com/glucauze/sd-webui-faceswaplab/discussions/23#discussioncomment-6640076_

**Comment by glucauze** [comment]
@sdcarterchen 

> version 1.2.0 is not as good as 1.1.2 ，

No
> and more complex operation

Yes. If you don't care about the options in faces, don't use them. It will be back to very simple.

> the swaped face is very blur : 

Yes. I was fearing that comment.

I disabled codeformer by default in Global Postprocessing. That's why you get poor results. Activate it and that will be back to what you know. You can make it the default in global settings.


Here are back to 1.1.2 default settings : 

![default_settings](https://github.com/glucauze/sd-webui-faceswaplab/assets/137925069/0cfdc09c-36ce-4cb4-96a4-ddb0a9d4aee4)

Here are my advanced default settings : 

![my_settings](https://github.com/glucauze/sd-webui-faceswaplab/assets/137925069/803f2766-2b45-4105-986d-7e502cfef6ef)

**Comment by sdcarterchen** [comment]
Thank you very much. These settings are very useful to me.
