### ISSUE TITLE
Confused about the basic usage of this extension

### ISSUE THREAD

**Issue by jeekca** [glucauze/sd-webui-faceswaplab#42]
Hi!

I’m so sorry for asking such a basic/novice question. I am not new to SD, Automatic1111 or extensions, and yet, I can’t get FaceSwap to work despite reading the doc multiple times.

I guess one way to frame my question is: I have a reference image and an image sequence. How do I use the extension to swap the face found in my image sequence with the provided reference image?

Since my image sequence wasn’t generated by SD, I guess I shouldn’t use the extension within the Text2Img and Img2Img tabs, but use the FaceSwap tab? But in this tab, unless I’m missing something, there is no button to trigger the swapping (i.e. "Generate")?

Again, my apologies for asking such a basic question. Beyond this, the advanced settings make sense and I’m excited to batch-swap once I can get past this admittedly simple issue.

Thanks!

**Comment by jeekca** [comment]
Ah. My bad. I wish I had played around a tiny bit more before posting this.

I was right about using the FaceSwapLab > Batch Process tab exclusively, where I put a face in Face 1 and then drag/dropped my image sequence in the Source Images tab.

Closing this. Thanks!

**Comment by AwesomeLemon** [comment]
I was confused about the same exact thing, thank you for posting the solution!
