### ISSUE TITLE
Close dialog

### ISSUE THREAD

**Issue by dhwz** [glucauze/sd-webui-faceswaplab#52]
Can you please make this dialog optional, it's really annoying to me.

https://github.com/glucauze/sd-webui-faceswaplab/blob/main/javascript/faceswap.js

FYI
There is also this extension adding the same thing for people which want such a dialog message.
https://github.com/w-e-w/sdwebui-close-confirmation-dialogue

**Comment by glucauze** [comment]
Sure i can remove it. I did this because gradio tends not to work fast enough and I'm losing my configuration.
