### ISSUE TITLE
Web UI takes longer to load

### ISSUE THREAD

**Issue by Berto665** [glucauze/sd-webui-faceswaplab#60]
After enabling the extension and restating the UI, it takes stable diffusion awhile to start. It will start to show loading icons on the top areas where the checkpoint dropdown is, and on the clipskip and SDVAE option that i also have there. When that stops "loading" it will start a loading icon on the extensions in the extension tab. Total time takes 71 sec rather 18 seconds with it disabled. Not sure what its loading, or looking through. Or if its a feature im not aware of that i need to disable. 

![bandicam 2023-08-22 23-55-16-596](https://github.com/glucauze/sd-webui-faceswaplab/assets/49830196/b9971acd-48f7-4b5e-a040-42cabb764091)

**Desktop**
 - OS: WIN10
 - Browser chrome

**Comment by glucauze** [comment]
This is due to the way i manage default settings.

I am working on it.
