### ISSUE TITLE
settings are not taken into account since v1.2.3

### ISSUE THREAD

**Issue by glucauze** [glucauze/sd-webui-faceswaplab#62]
**Problem** : Settings are not taken into account when modified.

**Reason** : 
This is due to the way settings are no manage. Instead of using a lambda to load the settings (which takes a lot of time), i removed the settings from ui-config.json. This allows to manage the settings a lot more quickly.

**Solution** : 
Migration : YOU NEED TO recreate ui-config.json (delete and restart sd) OR at least remove any faceswaplab reference in the ui-config.json file to be able to use default settings again.

See this for explainations : https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6109

**Comment by abline11** [comment]
Unfortunately your mitigation that '
YOU NEED TO recreate ui-config.json (delete) or at least remove any faceswaplab reference to be able to use default settings again' doesn't work.

Having tried both deleting the ui-config.json file entirely so it is recreated AND editing the ui-config.json file to remove all lines referencing faceswaplab it will not remember any of the settings put into the txt2img tab under the FaceSwapLab V1.2.3 pull down in between sessions (i.e. if I go to the Setting tab, then the Defaults option, then click on View Changes, then Apply).  In fact, it doesn't even pick up that there are any changes when View Changes is pressed.  For example any changes to add a default Face Checkpoint (precedence over reference face) or Genger are not recognised and therefore forgotten.

I even deleted the entire FaceSwapLab extension, and the associated folders for FaceSwapLab in the Models and Extensions folders, and deleted the ui-config.json and once FaceSwapLab was reinstalled fresh still any changes applied in the txt2img tab are not remembered or even recognised when I have tried to set Defaults via the Settings tab.

This is a great extension.  Please could you look at this again?

**Comment by glucauze** [comment]
Ok, reverting back would be easy but i need to be sure there is a problem first because the new way of handling parameters reduces load time drastically.

I have tested on linux on sdnext and a1111. I will try to test on windows.

What is your configuration ?

**Comment by abline11** [comment]
Hi, 

 

I have a Windows 11 Alienware Laptop and am using standard A1111.

 

Just to be sure I also reinstalled a completely new clean version of A1111 and just added one single extra extension (i.e. FaceSwapLab) and it doesn’t work to remember any defaults set in the txt2img tab for FaceSwapLab.

 

Regards,

 

Andrew Brown

**Comment by glucauze** [comment]
Ok, just to be sure because it's puzzling me.

You are using these setting : 

![](https://user-images.githubusercontent.com/137925069/258478052-0cfdc09c-36ce-4cb4-96a4-ddb0a9d4aee4.png)

And these settings are not reflected in txt2img parameters?

Or you are expecting the configuration done in txt2img to be persistent ?

**Comment by abline11** [comment]
Hi,

 

The settings under FaceSwapLab section are fine.

 

The settings under txdt2img which you should be able to make persistent by going to Settings/Default section are now not being stored as persistent or even recognised as changes you can view (see attached 2 screen shots).  

 

If, for example,  I change the Face Checkpoint to Face_3.safetensors it is impossible to make it persistent like all other changes in txt2img (e.g. Restore Faces or Seed)

 

I expect the configurations done in txt2img to be persistent as they always are if you use the Settings/Default.  This facility has been available for months in A1111 and worked perfectly in V1.2.2, but is now broken in V1.2.3.  Have you never used or tested the Settings/Default facility in A1111?

 

King regards,

 

Andrew Brown

**Comment by glucauze** [comment]
Ok thanks ! I got it : 

> If, for example,  I change the Face Checkpoint to Face_3.safetensors it is impossible to make it persistent like all other changes in txt2img (e.g. Restore Faces or Seed)

I made settings do_not_save to be able to adjust settings by myself.

> I expect the configurations done in txt2img to be persistent as they always are if you use the Settings/Default.  This facility has been available for months in A1111 and worked perfectly in V1.2.2, but is now broken in V1.2.3.  Have you never used or tested the Settings/Default facility in A1111?

I don't use this option. That's why. Settings cannot be managed by faceswaplab OR sd. I had to made a choice but but I applied this to all the changes.

 I will try to think of a way to handle that properly. I hope it's not too critical in the meantime.

**Comment by glucauze** [comment]
I made a change to mark only fields that are not managed in faceswaplab settings. I think it is working. Would you have time to try and tell me if it is better for you ?

**Comment by glucauze** [comment]
Don't worry about that, since all the tests are ok and the change is not critical, i will merge the version. You can tell me if it's better by just reinstalling the main branch.

**Comment by glucauze** [comment]
Reopening (the merge has closed the issue). Will close if you confirm it works properly.

**Comment by abline11** [comment]
It certainly seems to now recognise the changes I make in txt2img and, via the Setting/Defaults section, allow me to both view the changes I have made and save them for the next time I open A1111 (see attached screenshot).

 

Well done for such a quick fix!

**Comment by abline11** [comment]
Thank you very much.
