### ISSUE TITLE
Fixed model seed for face inpainting

### ISSUE THREAD

**Issue by Neocaron** [glucauze/sd-webui-faceswaplab#70]
Hello there, maybe I'm missing something but when I use Post-Inpainting (After swapping) or even pre, if I set a fixed seed in the img to img tab, the seed inside the extension still changes everytime for the face. Any way to use the same seed as the one define in the main setting? Or at least not have it change at every generation? Maybe it's possible to define the seed in the face Inpainting prompt tab already?

Great extension by the way!

**Comment by glucauze** [comment]
Yes i do not fix the seed in the generation. I could reuse the same seed or make the seed an option. Will see if i have time to do that.

**Comment by Neocaron** [comment]
Thank you it would render batch generation with inpainting way more useful. You have a great day!

**Comment by glucauze** [comment]
I've added the option in version 1.2.5.

It was a bit of a pain to get the same seed as the generation, so I started with a default seed of 0.
