### ISSUE TITLE
Face Swap does not trigger consistently

### ISSUE THREAD

**Issue by tokenwizard** [glucauze/sd-webui-faceswaplab#80]
**Please remember that the bug report section is not a forum. Before submitting a bug, ensure you have read the FAQ thoroughly. This helps us maintain an efficient bug tracking process. Thank you for your understanding and cooperation. Use the discussion section for anything else.**

**Describe the bug**
I will be generating image after image with successful face swap using this plugin. But then suddenly the next image does not get the face swapped. After generating a few more images or switching the face model, it will work again for a while but eventually stops working again. 

**To Reproduce**
1. Train a Face Checkpoint using the FaceSwapLab tab, Batch Source Images and name it whatever you like
2. Use Txt2Img or Img2Img to generate a new image with your trained face checkpoint listed in the FaceSwapLab section and Enabled
3. Repeat Generation without changing any settings or prompt
4. Eventually the generated images will not get the face swapped

**Expected behavior**
The Face Checkpoint should continue to be applied as long as it is set and enabled. 

**Screenshots**
Here you can see console output where Inswapper was triggered for the first image generation, but then the second one did not trigger Inswapper, so the face did not get swapped:
![image](https://github.com/glucauze/sd-webui-faceswaplab/assets/24832561/a800bd09-5903-4b17-9f79-9b3e89e2b23e)

Here is the First Image with has my face 
![00012-1806140301-swapped](https://github.com/glucauze/sd-webui-faceswaplab/assets/24832561/d0857dd2-fac2-492b-bfc5-d5c9023df95a)

And the second which doesn't.
![00013-357905843-swapped](https://github.com/glucauze/sd-webui-faceswaplab/assets/24832561/aabab941-7aca-4844-bd23-dcb003af8019)

**Desktop (please complete the following information):**
![image](https://github.com/glucauze/sd-webui-faceswaplab/assets/24832561/b8a193f9-a6c5-4018-9eca-17973e43b0eb)

Firefox 116.0.3

**Comment by glucauze** [comment]
Ok that's weird. Are you experimenting the bug when you are selecting an image with the same seed again ? I don't have that problem ?

**Comment by tokenwizard** [comment]
I did not touch any settings between generating those two photos. The Seed was left at the default value in Automatic1111 webui of "-1" and other than setting the Face Checkpoint and checking the Enable checkbox before generating the first picture, I did not change anything in the FaceSwapLab section:
![image](https://github.com/glucauze/sd-webui-faceswaplab/assets/24832561/84533428-b1ac-4722-b3be-8a0ab4a89f11)


Literally I set all the settings and clicked Generate twice; the first one applied the face swap and the second one didn't. 

But it seems random as to how many will work before it starts failing to swap the face.

**Comment by glucauze** [comment]
Yep that's why it could be interesting to fix the seed to see if it appears randomly or for some specific seeds. If it works half the time for a given seed, that would mean there is a bug. If not, it can be related to the nsfw setting in sd. Try setting to 1 to disable filtering and see if it does solve the problem.

**Comment by tokenwizard** [comment]
> Yep that's why it could be interesting to fix the seed to see if it appears randomly or for some specific seeds. If it works half the time for a given seed, that would mean there is a bug. If not, it can be related to the nsfw setting in sd. Try setting to 1 to disable filtering and see if it does solve the problem.

Are you referring to this NSFW setting? 
![image](https://github.com/glucauze/sd-webui-faceswaplab/assets/24832561/b53b9ebb-0e77-436f-9d87-c32ee979f167)

**Comment by glucauze** [comment]
Yes
